### PR TITLE
fix: make the project startable and fix some issues:

### PR DESCRIPTION
**Pull request by amtyurin**
1 - scenario load message is shown after scenario is loaded
2 - update dependencies, old ones do not exist anymore

### CODE REVIEW

**Comment by Trilarion** [comment]
Thanks, I will have a look at it.

**Comment by Trilarion** [comment]
Looks good to me. If you plan to contribute more, I'm looking forward to it.

**Comment by amtyurin** [comment]
Thanks,

I believe you do not have time to work with it right now. May be you have some roadmap/docs with proposed mocks/design/behavior or any person who can help to understand existing architecture?


Thanks,
Andrey

**Comment by Trilarion** [comment]
Yes, currently I do not have time for the project unfortunately. There is a design document, see https://github.com/Trilarion/imperialism-remake/tree/master/documentation/definition and https://imperialism-remake-definition.readthedocs.io/en/latest/ and a development document, see https://github.com/Trilarion/imperialism-remake/tree/master/documentation/development and https://imperialism-remake-developer.readthedocs.io/en/latest/ but I fear it does not feature many UI mocks.

The examples in https://github.com/Trilarion/imperialism-remake/tree/master/examples may explain a bit the existing architecture. Basically there is one process for the local server and one process for the client and they communicate over QTcpSockets (https://doc.qt.io/qt-5/qtcpsocket.html). The Server (and the Scenario Editor) has a full fledged Scenario (https://github.com/Trilarion/imperialism-remake/blob/master/source/imperialism_remake/server/scenario.py), while the client typically is to see only a smaller client Scenario, only containing the information that is needed for each client.

If you want to discuss the architecture and other things, it's probably best to use the Issues here or the forum (https://remake.twelvepm.de/forum/). I just activated your account there. Feel free to ask anything about the project.

**Comment by Trilarion** [comment]
The readthedocs HTML renderings are not built new with every commit. They should be it seems to have been broken. However, they should show the latest state anyway.

**Comment by Trilarion** [comment]
I also put some roadmap information in the Projects tab here on Github.

https://github.com/Trilarion/imperialism-remake/projects

**Comment by Trilarion** [comment]
And I wanted to make prototypes of parts of the game (map, trade system, battle system) before integrating them in the game.

**Pull request merged**
