### PR TITLE
Features: cursor change, turn action

### PR DESCRIPTION
**Pull request by amtyurin**
- allow workers action based on its skill and tech available (just some examples)
- change cursor based on action available (not fully implemented yet)
- add turn prototype (no server messages yet, just local client change for now) and worker action execution for the turn

### CODE REVIEW

**Comment by Trilarion** [comment]
I cherry picked the three new commits and added one on my own. See https://github.com/Trilarion/imperialism-remake/commits/master

I could not integrate this pull request as is, because you merged the master here into your master branch. That created a merge commit and resulted in the same state, but not in the same history. The history is different.

I suggest that you reset your master branch instead with something like 

git remote add upstream https://github.com/Trilarion/imperialism-remake.git
git reset --hard upstream/master
git push

if you have not committed anything in the meantime! If you have, you would need to preserve the commits in between!

**Comment by amtyurin** [comment]
Just did that,
I needed to add git fetch upstream and do force push for my branch.

**Comment by Trilarion** [comment]
Right. Now we are completely equal and all future Pull requests should go smoothly.

**Comment by Trilarion** [comment]
I described the current state of the network communication in the forum. See https://remake.twelvepm.de/forum/viewtopic.php?f=10&t=1551

**Comment by amtyurin** [comment]
Ok, thanks! I’ve added some question there

**Pull request closed without merging**
